version: '2'

services:
  citizen-ui:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/civil/citizen-ui
    ports:
      # TODO: change this mapping to map the port your application listens on
      - 3000:3000
