apiVersion: v2
appVersion: "1.0"
description: Helm chart for the HMCTS Civil Citizen Frontend service
name: civil-citizen-ui
home: https://github.com/hmcts/civil-citizen-ui
version: 0.0.4

maintainers:
  - name: HMCTS CMC Dev Team
    email: cmc-developers@HMCTS.NET
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: '@hmctspublic'

  - name: idam-pr
    version: 2.2.7
    repository: '@hmctspublic'
    condition: idam-pr.enabled

  - name: cmc-claim-store
    version: 4.1.32
    repository: '@hmctspublic'
    condition: cmc-claim-store.enabled

