apiVersion: v2
appVersion: "1.0"
description: Helm chart for the HMCTS Civil Citizen Frontend service
name: civil-citizen-ui
home: https://github.com/hmcts/civil-citizen-ui
version: 0.0.4

maintainers:
  - name: HMCTS CMC Dev Team
    email: cmc-developers@HMCTS.NET
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: '@hmctspublic'

  - name: idam-pr
    version: 2.2.7
    repository: '@hmctspublic'
    condition: idam-pr.enabled

  - name: cmc-claim-store
    version: 4.1.27
    repository: '@hmctspublic'
    condition: cmc-claim-store.enabled

  - name: postgresql
    version: 10.13.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: ccd
    version: 6.0.0
    repository: '@hmctspublic'
    condition: ccd.enabled

  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled

  - name: elasticsearch
    version: 7.8.1
    repository: '@hmctspublic'
    condition: elastic.enabled

  - name: logstash
    version: 2.4.1
    repository: '@hmctspublic'
    condition: elastic.enabled
