security:
  referrerPolicy: 'origin'
port: 3001
timeout: 30000
services:
  civilService:
    url: 'http://localhost:8765'
    microservice: 'civil_service'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'civil_citizen_ui'
    clientSecret: 'TBC'
health:
  timeout: 5000
  deadline: 15000
appInsights:
  instrumentationKey:
